language: java

services:
  - docker

before_install:
- docker pull reactnativecommunity/react-native-android

script:
- docker run --rm --name hei -v $PWD:/pwd -w /pwd reactnativecommunity/react-native-android bash -c "yarn install && ./gradlew assembleRelease"
